/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/nike_zoom_pegasus_shoe_by_digitworlds.com.glb
Author: Przemek Gesicki - DigitWorlds (https://sketchfab.com/DigitWorlds)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nike-zoom-pegasus-shoe-by-digitworldscom-155fe25d6c9f4958b07df9f2d9b8833c
Title: Nike Zoom Pegasus Shoe by DigitWorlds.com -
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HomeScreen3d(props) {
  const { nodes, materials } = useGLTF(
    "/nike_zoom_pegasus_shoe_by_digitworlds.com.glb"
  );

  return (
    <>
      {/* <fog attach="fog" args={["black", 0, 50]} />
      <directionalLight position={[0, 5, 5]} intensity={1} castShadow />
      <pointLight position={[0, 20, 0]} intensity={0.3} castShadow /> */}
      <group
        {...props}
        dispose={null}
        scale={0.6}
        position={[-1, 6, -2.3]}
        rotation={[0, -0.2, 0.2]}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material}
          position={[-2, 3, 2]}
        />
      </group>
    </>
  );
}

useGLTF.preload("/nike_zoom_pegasus_shoe_by_digitworlds.com.glb");
