/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MUSHROOM_BUILDS (https://sketchfab.com/MUSHROOM_BUILDS)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nike-air-jordans-1-retro-mid-fog-canvas-scan-eb97944e2d0c42fe9b8c530968abd2ba
title: Nike Air Jordans 1 Retro Mid Fog (Canvas) Scan
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, a } from "@react-spring/three";
export function Nike(props) {
  const { nodes, materials } = useGLTF(
    "../../..//nike_air_jordans_1_retro_mid_fog_canvas_scan.glb"
  );

  const handleOpen = () => {
    props.setOpen(!props.open);
  };
  const openThreeAnimation = useSpring({
    rotation: props.open ? [0, 0, 0] : [1.61, 0, 0],
    position: props.open ? [0, -1.5, 0] : [0, 0, 0],
  });
  return (
    <>
      <fog attach="fog" args={["black", 0, 30]} />
      <ambientLight intensity={0.4} />
      <directionalLight
        position={[-8, 16, -8]}
        intensity={0.3}
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        shadow-camera-far={50}
        shadow-camera-left={-10}
        shadow-camera-right={10}
        shadow-camera-top={10}
        shadow-camera-bottom={-10}
      ></directionalLight>
      <pointLight position={[0, 20, 0]} intensity={0.8} />

      <group onClick={handleOpen} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <a.group
              position={[0, -0.3, -3]}
              rotation={[-0.8, 0.3, 3.4]}
              scale={1.4}
            >
              <mesh
                geometry={nodes.Object_4.geometry}
                material={materials.JordanBottom}
              />
              <mesh
                geometry={nodes.Object_5.geometry}
                material={materials.JordanBottom}
              />
              <mesh
                geometry={nodes.Object_6.geometry}
                material={materials["Jordans.001"]}
              />
              <mesh
                geometry={nodes.Object_7.geometry}
                material={materials["Jordans.001"]}
              />
            </a.group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("../../../nike_air_jordans_1_retro_mid_fog_canvas_scan.glb");
