/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/nike_sb_photoscan.glb
Author: 3djon (https://sketchfab.com/3djon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-sb-photoscan-2ce1c205c1f94c7db2d1af072e8b75b4
Title: Nike SB Photoscan
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function NikeSb(props) {
  const { nodes, materials } = useGLTF("/nike_sb_photoscan.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.prop_nike_a_01__0.geometry}
            material={materials["Scene_-_Root"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.03}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/nike_sb_photoscan.glb");
