/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/nike_air_max_skor.glb
Author: Punktasky (https://sketchfab.com/Punktasky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-max-skor-91e4b7e1bb8d4983a1120c6a0935ca99
Title: Nike Air Max Skór
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, a } from "@react-spring/three";

export function NikeSkor(props) {
  const { nodes, materials } = useGLTF("/nike_air_max_skor.glb");
  return (
    <>
      <fog attach="fog" args={["white", 0, 30]} />
      <ambientLight intensity={0.4} />
      <directionalLight
        position={[-8, 16, -8]}
        intensity={0.3}
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        shadow-camera-far={50}
        shadow-camera-left={-10}
        shadow-camera-right={10}
        shadow-camera-top={10}
        shadow-camera-bottom={-10}
      ></directionalLight>
      <pointLight position={[0, 50, 0]} intensity={0.3} />
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.16}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <a.group position={[-3.69, -2, -7]} rotation={[1.4, -0.8, 3]}>
              <mesh
                geometry={nodes.Object_2.geometry}
                material={materials.NikeAirMaxSkor_100k_tex_fix_u1_v1}
              />
              <mesh
                geometry={nodes.Object_3.geometry}
                material={materials.NikeAirMaxSkor_100k_tex_fix_u1_v1}
              />
            </a.group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/nike_air_max_skor.glb");
