/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/nike_sb_photoscan.glb
Author: 3djon (https://sketchfab.com/3djon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-sb-photoscan-2ce1c205c1f94c7db2d1af072e8b75b4
Title: Nike SB Photoscan
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function NikeSb(props) {
  const { nodes, materials } = useGLTF("/nike_sb_photoscan.glb");
  return (
    <>
      <fog attach="fog" args={["black", 0, 40]} />
      <ambientLight intensity={0.4} />
      <directionalLight
        position={[-8, 16, -8]}
        intensity={0.3}
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        shadow-camera-far={50}
        shadow-camera-left={-10}
        shadow-camera-right={10}
        shadow-camera-top={10}
        shadow-camera-bottom={-10}
      ></directionalLight>
      <pointLight position={[0, 50, 0]} intensity={0.9} />
      <group {...props} dispose={null}>
        <group
          rotation={[-Math.PI / 2, 0.5, 0]}
          scale={0.041}
          position={[-0.7, -0.7, -0.3]}
        >
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.prop_nike_a_01__0.geometry}
              material={materials["Scene_-_Root"]}
              rotation={[-1.8, -0.2, 2.1]}
              scale={0.5}
            />
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/nike_sb_photoscan.glb");
