/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/nike_fotball_shoe.glb
Author: Dan-Levi Tømta (https://sketchfab.com/danbannan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-fotball-shoe-2247602d99284d689a419f1dd3f07de4
Title: Nike Fotball Shoe
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function NikePhantom(props) {
  const { nodes, materials } = useGLTF("/nike_fotball_shoe.glb");
  return (
    <>
      <fog attach="fog" args={["white", 0, 30]} />
      <ambientLight intensity={0.4} />
      <directionalLight
        position={[-8, 16, -8]}
        intensity={0.3}
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        shadow-camera-far={50}
        shadow-camera-left={-10}
        shadow-camera-right={10}
        shadow-camera-top={10}
        shadow-camera-bottom={-10}
      ></directionalLight>
      <pointLight position={[0, 50, 0]} intensity={0.9} />
      <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-1, -0.5, -1]}
            scale={0.3}
            rotation={[-1.8, 0, 3.5]}
          >
            <mesh
              geometry={nodes.Object_2.geometry}
              material={materials.Material__35}
            />
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/nike_fotball_shoe.glb");
