// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.1.2 public/scene.gltf
// Author: ryanbair (https://sketchfab.com/ryanbair)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/nike-dunk-hawaii-6k-triangles-5a631f5439764fa18cf465f4cf19338f
// Title: Nike Dunk Hawaii - 6k triangles
// */

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";

// export function NikeHawaii(props) {
//   const { nodes, materials } = useGLTF("/scene.gltf");
//   return (
//     <group
//       {...props}
//       dispose={null}
//       rotation={[0.3, 2, -0.3]}
//       position={[0, 0, 0]}
//     >
//       <mesh
//         geometry={nodes.Object_2.geometry}
//         material={materials.tex_u1_v1}
//         rotation={[-Math.PI / 2, 0, 0]}
//         scale={0.28}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/scene.gltf");
