/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/yellow_nike_dunk_low_dusty_olive_from_video_clip.glb
Author: ryanbair (https://sketchfab.com/ryanbair)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yellow-nike-dunk-low-dusty-olive-from-video-clip-93be9098ab9c46329cbeae98f458a912
Title: Yellow Nike Dunk Low Dusty Olive from video clip
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function NikeDunkLow(props) {
  const { nodes, materials } = useGLTF(
    "/yellow_nike_dunk_low_dusty_olive_from_video_clip.glb"
  );
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
      <group position={[-0.06, 2.25, -2.2]} rotation={[-1.44, 0, 0]} scale={1}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.tex_u1_v1}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.tex_u1_v1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/yellow_nike_dunk_low_dusty_olive_from_video_clip.glb");
