export const CYBER_ORDER_CREATE_REQUEST = "CYBER_ORDER_CREATE_REQUEST";
export const CYBER_ORDER_CREATE_SUCCESS = "CYBER_ORDER_CREATE_SUCCESS";
export const CYBER_ORDER_CREATE_FAIL = "CYBER_ORDER_CREATE_FAIL";

export const CYBER_ORDER_DETAILS_REQUEST = "CYBER_ORDER_DETAILS_REQUEST";
export const CYBER_ORDER_DETAILS_SUCCESS = "CYBER_ORDER_DETAILS_SUCCESS";
export const CYBER_ORDER_DETAILS_FAIL = "CYBER_ORDER_DETAILS_FAIL";

export const CYBER_ORDER_PAY_REQUEST = "CYBER_ORDER_PAY_REQUEST";
export const CYBER_ORDER_PAY_SUCCESS = "CYBER_ORDER_PAY_SUCCESS";
export const CYBER_ORDER_PAY_FAIl = "CYBER_ORDER_PAY_FAIl";

export const CYBER_ORDER_PAY_RESET = "CYBER_ORDER_PAY_RESET";
