export const CYBER_PRODUCT_LIST_REQUEST = "CYBER_PRODUCT_LIST_REQUEST";
export const CYBER_PRODUCT_LIST_SUCCESS = "CYBER_PRODUCT_LIST_SUCCESS";
export const CYBER_PRODUCT_LIST_FAIL = "CYBER_PRODUCT_LIST_FAIL";

export const CYBER_PRODUCT_DETAILS_REQUEST = "CYBER_PRODUCT_DETAILS_REQUEST";
export const CYBER_PRODUCT_DETAILS_SUCCESS = "CYBER_PRODUCT_DETAILS_SUCCESS";
export const CYBER_PRODUCT_DETAILS_FAIL = "CYBER_PRODUCT_DETAILS_FAIL";
